// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhoZsZf5AhSU7ZfG5_ZoxWRw1o2Ez62-c',
    appId: '1:56487979082:web:4a43d39d5758c0e78ddeb3',
    messagingSenderId: '56487979082',
    projectId: 'flutter-task-55cd6',
    authDomain: 'flutter-task-55cd6.firebaseapp.com',
    storageBucket: 'flutter-task-55cd6.appspot.com',
    measurementId: 'G-SJR7W0VS54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmXS61ohl3Dp-QtESVHAoHT8jIKoNC0ec',
    appId: '1:56487979082:android:721c20f128bdcce88ddeb3',
    messagingSenderId: '56487979082',
    projectId: 'flutter-task-55cd6',
    storageBucket: 'flutter-task-55cd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6A-uTxTlKbrzDmg5RuTdtuUYGcbkKx18',
    appId: '1:56487979082:ios:ebf2ff4f197c55ec8ddeb3',
    messagingSenderId: '56487979082',
    projectId: 'flutter-task-55cd6',
    storageBucket: 'flutter-task-55cd6.appspot.com',
    androidClientId: '56487979082-huqo28ael6okad6qbb1slgeip0703vnu.apps.googleusercontent.com',
    iosClientId: '56487979082-a494tic0gio954em157jrhp09c6nk29u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6A-uTxTlKbrzDmg5RuTdtuUYGcbkKx18',
    appId: '1:56487979082:ios:ebf2ff4f197c55ec8ddeb3',
    messagingSenderId: '56487979082',
    projectId: 'flutter-task-55cd6',
    storageBucket: 'flutter-task-55cd6.appspot.com',
    androidClientId: '56487979082-huqo28ael6okad6qbb1slgeip0703vnu.apps.googleusercontent.com',
    iosClientId: '56487979082-a494tic0gio954em157jrhp09c6nk29u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhoZsZf5AhSU7ZfG5_ZoxWRw1o2Ez62-c',
    appId: '1:56487979082:web:34b5a482d80e11158ddeb3',
    messagingSenderId: '56487979082',
    projectId: 'flutter-task-55cd6',
    authDomain: 'flutter-task-55cd6.firebaseapp.com',
    storageBucket: 'flutter-task-55cd6.appspot.com',
    measurementId: 'G-4QD697DHKR',
  );

}